#!/bin/sh

# shortcuts
alias nv="nvim"
alias c="clear"
alias la="ls -a"
alias ll="ls -la"

# colors
alias ls="ls --color=auto"
alias grep="grep --color=auto"
alias egrep="egrep --color=auto"
alias fgrep="fgrep --color=auto"

# confirm file overwrite
alias cp="cp -i"
alias mv="mv -i"
alias rm="rm -i"

# ensure that there is no other cmus instance
alias cmus="[ `pgrep cmus` ] && (killall cmus && cmus) || cmus"
