#!/bin/sh

source "/etc/X11/xinit/xinitrc.d/50-systemd-user.sh"

while true; do
   xsetroot -name "` date +"%R"`"
done &

xbindkeys -f "${XDG_CONFIG_HOME:-$HOME/.config}/X11/xbindkeysrc" # shortcuts

nitrogen --restore & # wallpaper
picom & # compositor
unclutter & # hide idle cursor

# systray
volumeicon &
nm-applet &

exec dwm # window manager
