#!/bin/sh

# shortcuts
alias nv="nvim"
alias c="clear"
alias la="ls -a"
alias ll="ls -la"

# colors
alias ls="ls --color=auto"
alias grep="grep --color=auto"
alias egrep="egrep --color=auto"
alias fgrep="fgrep --color=auto"

# confirm file overwrite
alias cp="cp -i"
alias mv="mv -i"
alias rm="rm -i"

# git alias
alias m="git checkout master"
alias gc="git checkout"
alias push="git push origin/master"
alias com="git commit"
alias gs="git status"
alias gl="git log"
