#!/bin/sh

# git status
autoload -Uz vcs_info
precmd_vcs_info() { vcs_info }
precmd_functions+=( precmd_vcs_info )
setopt prompt_subst

# prompt
PROMPT='%(?.%F{red}❯%F{green}❯%F{yellow}❯%f .%F{red}%B%?❯%f%b )'
RPROMPT='%B%F{blue}%1~%b%F{yellow}${vcs_info_msg_0_}%f'
zstyle ':vcs_info:git:*' formats ' %b'
