[theme]
primary = "light white"
secondary = "light black"
title = "green"
playing = "green"
playing_selected = "black"
highlight = "black"
highlight_bg = "white"
error = "light white"
statusbar = "white"
statusbar_progress = "green"
cmdline = "light white"
search_match = "light red"
